spring:
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: https://github.com/viplavfauzdar/spring-cloud-config
          search-paths:
          - config-server-files
management:
  endpoint:
    restart:
      enabled: true
